[features]
seeds = false
skip-lint = false
[programs.localnet]
solanapdas = "3TT1RmUyN6SZaoVPPSHPNse3WgP9CaK5Zan3yuMFSMZS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localhost"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
